// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/bsymbreg.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kalman
List kalman(mat x, vec y, mat theta, double V, mat E, double lambda, Nullable<double> kappa);
RcppExport SEXP _bsymbreg_kalman(SEXP xSEXP, SEXP ySEXP, SEXP thetaSEXP, SEXP VSEXP, SEXP ESEXP, SEXP lambdaSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    Rcpp::traits::input_parameter< mat >::type E(ESEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman(x, y, theta, V, E, lambda, kappa));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bsymbreg_kalman", (DL_FUNC) &_bsymbreg_kalman, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_bsymbreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
